services:
  web:
    build:
      context: https://github.com/pipe3/u-checker.git
    ports:
      - "5000:5000"
    volumes:
      - ${HOME}/u-checker/data:/data
    env_file:
      - ${HOME}/u-checker/u-checker.env
    environment:
      DATA_DIR: /data
    restart: unless-stopped

